name: Build and Deploy

# 触发 workflow 的事件，当有新push或者pr时执行
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# 一个workflow由执行的一项或多项job
jobs:
  build-and-deploy: # 自定义名称
    # 运行在虚拟机环境ubuntu-latest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout  ️ # 将代码拉取到虚拟机
        uses: actions/checkout@v3

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Deploy # 部署
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          # ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          branch: gh-pages # 部署后提交到那个分支
          folder: dist # 这里填打包好的目录名称
